version: "2.4"

services:
  postgres:
    restart: always
    image: "postgres:10"
    environment:
      POSTGRES_PASSWORD: password_123456
    volumes:
      - "postgresdata:/var/lib/postgresql/data:delegated"
    healthcheck:
      interval: 30s
    ports:
      - "5432:5432"

  generic_nation:
    restart: always
    image: "generic_nation"
    command: python3 /data/generic_nation/server.py
    environment:
      FLASK_APP: /data/generic_nation/app.py
      FLASK_ENV: development
      PYTHONPATH: /data
    ports:
      - "5000:5000"
    volumes:
      - "./:/data:rw"
    depends_on:
      - "postgres"

volumes:
  postgresdata:
    driver: local


